//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.02.08 at 11:15:12 AM CET
//

package it.celi.semeval.questions;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import org.edits.EditsFactory;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the it.celi.semeval.questions package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory extends EditsFactory {

	private final static QName _Question_QNAME = new QName("", "question");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: it.celi.semeval.questions
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Question }
	 * 
	 */
	public Question createQuestion() {
		return new Question();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Question }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "question")
	public JAXBElement<Question> createQuestion(Question value) {
		return new JAXBElement<Question>(_Question_QNAME, Question.class, null, value);
	}

	/**
	 * Create an instance of {@link ReferenceAnswer }
	 * 
	 */
	public ReferenceAnswer createReferenceAnswer() {
		return new ReferenceAnswer();
	}

	/**
	 * Create an instance of {@link ReferenceAnswers }
	 * 
	 */
	public ReferenceAnswers createReferenceAnswers() {
		return new ReferenceAnswers();
	}

	/**
	 * Create an instance of {@link StudentAnswer }
	 * 
	 */
	public StudentAnswer createStudentAnswer() {
		return new StudentAnswer();
	}

	/**
	 * Create an instance of {@link StudentAnswers }
	 * 
	 */
	public StudentAnswers createStudentAnswers() {
		return new StudentAnswers();
	}

}
