//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.08 at 11:15:12 AM CET 
//


package it.celi.semeval.questions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Question complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Question">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="questionText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="referenceAnswers" type="{}ReferenceAnswers"/>
 *         &lt;element name="studentAnswers" type="{}StudentAnswers"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="module" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Question", propOrder = {
    "questionText",
    "referenceAnswers",
    "studentAnswers"
})
public class Question {

    @XmlElement(required = true)
    protected String questionText;
    @XmlElement(required = true)
    protected ReferenceAnswers referenceAnswers;
    @XmlElement(required = true)
    protected StudentAnswers studentAnswers;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "module")
    protected String module;

    /**
     * Gets the value of the questionText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuestionText() {
        return questionText;
    }

    /**
     * Sets the value of the questionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuestionText(String value) {
        this.questionText = value;
    }

    /**
     * Gets the value of the referenceAnswers property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceAnswers }
     *     
     */
    public ReferenceAnswers getReferenceAnswers() {
        return referenceAnswers;
    }

    /**
     * Sets the value of the referenceAnswers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceAnswers }
     *     
     */
    public void setReferenceAnswers(ReferenceAnswers value) {
        this.referenceAnswers = value;
    }

    /**
     * Gets the value of the studentAnswers property.
     * 
     * @return
     *     possible object is
     *     {@link StudentAnswers }
     *     
     */
    public StudentAnswers getStudentAnswers() {
        return studentAnswers;
    }

    /**
     * Sets the value of the studentAnswers property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudentAnswers }
     *     
     */
    public void setStudentAnswers(StudentAnswers value) {
        this.studentAnswers = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the module property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModule() {
        return module;
    }

    /**
     * Sets the value of the module property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModule(String value) {
        this.module = value;
    }

}
